@startuml

title __DTO's Class Diagram__\n

  package  {
    package DTO {
      class Category {
          - categoryId : Integer
          - categoryName : String
          + Category()
          + getCategoryId()
          + setCategoryId()
          + getCategoryName()
          + setCategoryName()
      }
    }
  }
  

  package  {
    package DTO {
      class EntryList {
          - userId : Integer
          - itemId : String
          - itemName : String
          - entryDate : String
          - itemStock : Integer
          - quantity : Integer
          + EntryList()
          + EntryList()
          + getItemStock()
          + setItemStock()
          + getItemName()
          + setItemName()
          + getUserId()
          + setUserId()
          + getItemId()
          + setItemId()
          + getEntryDate()
          + setEntryDate()
          + getQuantity()
          + setQuantity()
      }
    }
  }
  

  package  {
    package DTO {
      class Items {
          - itemId : String
          - itemName : String
          - itemPrice : Double
          - itemStock : Integer
          - categoryId : Integer
          - categoryName : String
          - storeId : Integer
          - storePlace : String
          - minimalStockLevel : Integer
          + Items()
          + Items()
          + Items()
          + getCategoryName()
          + setCategoryName()
          + getStorePlace()
          + setStorePlace()
          + getItemId()
          + setItemId()
          + getItemName()
          + setItemName()
          + getItemPrice()
          + setItemPrice()
          + getItemStock()
          + setItemStock()
          + getCategoryId()
          + setCategoryId()
          + getStoreId()
          + setStoreId()
          + getMinimalStockLevel()
          + setMinimalStockLevel()
      }
    }
  }
  

  package  {
    package DTO {
      class Sale {
          - saleId : String
          - itemId : String
          - itemName : String
          - itemPrice : Double
          - itemStock : Integer
          - userId : Integer
          - userName : String
          - saleDate : String
          - quantity : Integer
          - totalPrice : Double
          - saleTotalPrice : Double
          + Sale()
          + Sale()
          + Sale()
          + Sale()
          + Sale()
          + Sale()
          + Sale()
          + Sale()
          + getUserName()
          + setUserName()
          + getSaleTotalPrice()
          + setSaleTotalPrice()
          + getItemStock()
          + setItemStock()
          + getItemPrice()
          + setItemPrice()
          + getItemName()
          + setItemName()
          + getSaleId()
          + setSaleId()
          + getItemId()
          + setItemId()
          + getUserId()
          + setUserId()
          + getSaleDate()
          + setSaleDate()
          + getQuantity()
          + setQuantity()
          + getTotalPrice()
          + setTotalPrice()
      }
    }
  }
  

  package  {
    package DTO {
      class StoreLocation {
          - storeId : Integer
          - storePlace : String
          + StoreLocation()
          + StoreLocation()
          + getStoreId()
          + setStoreId()
          + getStorePlace()
          + setStorePlace()
      }
    }
  }
  

  package  {
    package DTO {
      class User {
          - userId : Integer
          - userName : String
          - userLevelId : Integer
          - userLevel : String
          - password : String
          - email : String
          - address : String
          - phNumber : String
          + User()
          + User()
          + User()
          + User()
          + getUserLevel()
          + setUserLevel()
          + getUserId()
          + setUserId()
          + getUserName()
          + setUserName()
          + getUserLevelId()
          + setUserLevelId()
          + getPassword()
          + setPassword()
          + getEmail()
          + setEmail()
          + getAddress()
          + setAddress()
          + getPhNumber()
          + setPhNumber()
      }
    }
  }
  

  package  {
    package DTO {
      class UserLevel {
          - userLevelId : Integer
          - userLevel : String
          + UserLevel()
          + UserLevel()
          + getUserLevelId()
          + setUserLevelId()
          + getUserLevel()
          + setUserLevel()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
